### ISSUE TITLE
[Request] Add top movies and TV series based on popularity

### ISSUE THREAD

**Issue by nihaals** [alberanid/imdbpy#185]
https://www.imdb.com/chart/toptv
https://www.imdb.com/chart/moviemeter

**Comment by alberanid** [comment]
would be cool. This is a good issue for anyone that wants to begin contributing. ;-)

**Comment by SiddharthaAnand** [comment]
Hi @alberanid @OrangutanGaming If no one is working on this, Can I start?

**Comment by alberanid** [comment]
@SiddharthaAnand : sure, and feel free to ask if you have problems.

Basically:
* create a new file in imdb/parser/http/ similar to topBottomParser.py (maybe chartParser.py or something like that)
* in it, you need to create 2 classes, one to parse /chart/toptv and one for /chart/moviemeter
* for the code of these two classes, use the other parsers as examples
* copy the structure of the _OBJECTS dict
* edit imdb/parser/http/\_\_init\_\_.py and look for occurences of "topBottomParser" and do something similar, to introduce two new methods to the IMDbHTTPAccessSystem class
* if possible name those methods like \_get_\chart\_toptv and \_get\_chart\_moviemeter
* in imdb/\_\_init\_\_.py create the matching methods without the underscore at the beginning and call the others - this is due because we have different way to access the IMDb's data, and we need to introduce the same method also on imdb/parser/s3/\_\_init\_\_.py if those data will ever be available in the future

**Comment by uyar** [comment]
I'm not sure but the advanced search method might be able to handle this with new parameters.

**Comment by alberanid** [comment]
This issue was implemented in https://github.com/alberanid/imdbpy/commit/5f8c6769ceebaa9bc674e29817816a64f3f73f0e
