### ISSUE TITLE
Website redesign

### ISSUE THREAD

**Issue by albemala** [alberanid/imdbpy#205]
Hi everyone!

I don't know where tickets related to the website should go, so I'm writing this here, apologies if it's the wrong place.

I am currently attending a UI design course and, as an exercise, I decided to redesign the current website. I thought it needed a fresh new look, so here it is: please comment, leave your feedback and thoughts. 

Thank you!

![Web 1280 – 1](https://user-images.githubusercontent.com/2332860/54640353-7f66e180-4a87-11e9-8d97-53dbe77f6bfc.png)
![Web 1280 – 2](https://user-images.githubusercontent.com/2332860/54640352-7f66e180-4a87-11e9-9ff1-58662cb32d24.png)
![Web 1280 – 3](https://user-images.githubusercontent.com/2332860/54640351-7f66e180-4a87-11e9-924a-f5ec030db6cc.png)
![Web 1280 – 4](https://user-images.githubusercontent.com/2332860/54640350-7f66e180-4a87-11e9-9480-560a371a81fc.png)
![Web 1280 – 5](https://user-images.githubusercontent.com/2332860/54640349-7ece4b00-4a87-11e9-8580-96fe8f3c7219.png)

**Comment by alberanid** [comment]
Cool! I like the dark theme. I also appreciate that the content stays the same, since rethinking everything would probably take too much time for me, at the moment.

When you are satisfied with the result, feel free to send me the sources (CSS and HTML if needed); the site is still hosted on sourceforge. At some point I may evaluate a switch to github sites, but not too soon.

As always, thank you very much!

**Comment by uyar** [comment]
Looks great to me too. Black and yellow are the colors of my high school :)

**Comment by albemala** [comment]
Hey, apologies for the late reply. I'm glad you like it! Unfortunately though, that's just a mockup, I don't have the code for it. I was hoping for someone from the community to develop it, and maybe, at this point, moving the code here on github as well?

Anywone interest in working on it?

**Comment by uyar** [comment]
I'll see if I can find some time to work on it.

@alberanid To host this on github pages under the address imdbpy.github.io, we need an organization named imdbpy, right? I think it's more appropriate if you create it. Or do you want to host it on alberanid.github.io/imdbpy?

**Comment by uyar** [comment]
OK, I went ahead and created the organization. I'll delete it if we decide not to use it.

**Comment by uyar** [comment]
I started implementing using lektor and bulma because these are what I'm familiar with. I did a similar project with those tools quite recently, so it's fairly straightforward for me. The home page as implemented so far is on https://imdbpy.github.io/

Let me know about fixes or improvements or anything as it progresses.

**Comment by albemala** [comment]
Hey, looks good so far! Tomorrow I will send you a css with the styling I used and the code of the current website, if I find it.

**Comment by albemala** [comment]
@uyar I put together some code with initial styling, it's not complete yet but it's a starting point.

I also added the current website code, so you can take the content from there.

I will add other styling in the next days, but let me know if you need something else!

[TEMP.zip](https://github.com/alberanid/imdbpy/files/3093913/TEMP.zip)
[imdbpy.zip](https://github.com/alberanid/imdbpy/files/3093914/imdbpy.zip)

**Comment by uyar** [comment]
@albemala I applied your code. A few notes:

- The navigation menu needs better support for small screens. A burger menu or something.
- header, main tags and aria attributes for accessibility?
- Wouldn't it better to use svg icons for twitter and github instead of png?

I'll migrate the content for the other pages soon.

**Comment by uyar** [comment]
@albemala And I see that the styling uses px units for many settings. Will that not hurt responsiveness?

**Comment by albemala** [comment]
As I said, the code I sent you was just a starting point, so feel free to add/changed it as needed. I can send you SVGs as well, no problem.

**Comment by alberanid** [comment]
thanks for the effort!  I agree that once it's ready (no hurry) we can move the homepage from sourceforge.

Sorry if at the moment I can't really help, but I;m dealing with a bad pharyngitis and fever. :-/

**Comment by uyar** [comment]
@alberanid Sorry to hear about your health, get well soon.

**Comment by uyar** [comment]
I'm continuing to build the site with the Lektor static site generator. I think it's great but if it doesn't feel natural for you we can look into something else.

I've copied home page content over from current site. I've created a new content type for news items to simplify news management. And I've fiddled with the CSS styles to try and make the page look better on mobile.

I've enabled Travis builds in order to deploy automatically upon pushing to the `website` repository.

@albemala I can give you write access if you would like to work directly on the repo. You can edit  `assets/static/main.css` also through GitHub's online editor. I can write brief instructions about how to add content to Lektor but you can probably figure it out yourself by looking at the `content` folder.

Templates are in the `templates` folder. IMO the main issue is putting the navigation items into a burger menu on small screens. That needs to be handled in the `templates/layout.html` file.

That's all for now.

**Comment by albemala** [comment]
@alberanid I hope you got better in the meantime!

@uyar Yes, please, if you could grant me write access I will take a look at it.
Thanks, I don't need instructions for now. I'll be in touch in case I need it.
Anyway, you did a great job so far!

**Comment by uyar** [comment]
@albemala I've sent you an invitation for the organization and you should have write access on the website repo. When you push something there, travis should pick up and redeploy the site.

**Comment by uyar** [comment]
I have mostly finished moving the content to the new design. I have fixed and/or removed some broken and dead links under the development page (missing official packages). Similarly for the ecosystem page. I haven't finished the ecosystem page, several entries at the end of the current page are missing.

We can move tracking issues about the new site using the issues of that repository.

**Comment by alberanid** [comment]
ok! Let me know if I can help with some task, especially the boring ones. :-)

**Comment by uyar** [comment]
It would be great if you could go over the downloads and ecosystem pages and tell me which external links (packages and projects) you want to keep. Some of them are way too outdated and some are just plain dead. I've removed the dead ones and updated the ones I could find but a second set of eyeballs would be nice. You could also decide to keep some of the dead links. Or maybe introduce a "historical" section?

Or, I could just blindly copy anything over from the existing site. But I've already updated some of the links and it wouldn't make sense to break them again, I guess. What do you think?

**Comment by uyar** [comment]
Or, better still, just go ahead and directly edit the sources. My work on the structure is done, I just want to make a change about the sass/grunt build process but that wouldn't affect the content.

I've written some notes about how to work on the sources. If anything is unclear, let me know.

**Comment by alberanid** [comment]
closed, since the new website is online
