### ISSUE TITLE
Add ability to parse only certain seasons

### ISSUE THREAD

**Issue by ctlaltdefeat** [alberanid/imdbpy#245]
It'd be nice to have the ability to request info for episodes of only certain seasons of a TV series, so that only those seasons will be parsed.
This is especially pronounced for long-running, frequent shows: getting information about a specific numbered episode requires waiting for the parsing of all seasons to complete.

**Comment by deg3x** [comment]
I'd like to work on this feature if noone else is currently on it. @alberanid do you have any preferences/recommendations on the implementation approach?

**Comment by alberanid** [comment]
hi @deg3x ; I'm open to any solution.

To begin with, let's see an example:

```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import imdb

ia = imdb.IMDb()
er = ia.get_movie('0108757')
ia.update(er, 'episodes')
episodes = er['episodes']
print(episodes)
```

here 'episodes' is incomplete, since https://www.imdb.com/title/tt0108757/episodes only show the last season.

A good start would be to collect all the seasons.

Please do not consider this a proper solution, since I may be wrong on some details; an example:
* in the DOMHTMLSeasonEpisodesParser class of imdb.parser.http.movieParser I'd add a rule to extract (let's call this key "seasons-list") the values of the "bySeason" select.
* this "seasons-list" can be used in the imdb.parser.http__init__ module (get_movie_episodes method) to call itself, modifying the url, and collect also the missing seasons. This can be done adding an optional parameter to get_movie_episodes itself: if None, it fetches all the seasons, otherwise just one

After that, how to integrate the ability to just fetch the data of a single season is not so simple.
Consider that the "get_movie_episodes" should be considered an internal method (it's not part of the exposed and documented API).
Maybe we could add it as an helper (imdb.helpers module) or introduce a special update_series_seasons in the IMDb class.

Anyway, as said anything that works and doesn't break the existing API is fine for me.

**Comment by deg3x** [comment]
@alberanid Are you sure that is the case with your example? For me, using the latest imdbpy, your example returns a dictionary with the number of season as keys and a dictionary with all the episodes as a Movie class as values, for all the seasons of a series.

**Comment by alberanid** [comment]
@deg3x : you are absolutely correct, I was testing an old version.  I will look at the PR as soon as possible, thank you very much for your help!
