### ISSUE TITLE
Original title must not be locale-dependant (as it's the *original* title)

### ISSUE THREAD

**Issue by facundobatista** [alberanid/imdbpy#251]
#### Issue description

The `original title` key translates the title. It should not.

#### Version of IMDbPY, Python and OS

- **Python:** `3.6.9`
- **IMDbPY:** `6.9dev20200125` (installed from the repo here)
- **OS:** `uname_result(system='Linux', node='blackfx', release='4.15.0-76-generic', version='#86-Ubuntu SMP Fri Jan 17 17:24:28 UTC 2020', machine='x86_64', processor='x86_64')`

#### Steps to reproduce the issue

```
#!python

>>> from imdb import IMDb
>>> imdb = IMDb()
>>> m = imdb.get_movie('3606756')
>>> m
<Movie id:3606756[http] title:_Incredibles 2 (2018)_>
>>> m['original title']
'Los increíbles 2 (2018)'
```

#### What's the expected result?

`'Incredibles 2 (2018)'`

#### What's the actual result?

`'Los increíbles 2 (2018)'`

#### Additional details

Don't know why it's mistakenly translated to Spanish. Maybe because my `LANG` is `es_AR.UTF-8`. However if I start the Python prefixing it with `LANG=C`, still produces the wrong result.

**Comment by alberanid** [comment]
I think it's a combination of factors; IMDb probably decides to present a title also based on the IP of the request.

I suppose it should be possible to always get the original title: I think the information is present in the HTML.

**Comment by Philippe-Cholet** [comment]
About [title rules](https://github.com/alberanid/imdbpy/blob/master/imdb/parser/http/movieParser.py#L252), "title" seems to refer to the original title, while "original title" would be the translated title (when there is translation because of the IP). In my opinion, we could just switch them, or rename "original title" to a better name like "local title" since "translated title" would mean nothing when requesting from the country that made the movie (or that has the same language at least).

**Comment by alberanid** [comment]
now that #312 by @frleder is merged, we have access to (using https://www.imdb.com/title/tt2991224/reference as a reference):

* **localized title**: Tangerines - Mandarini
* **original title**: Mandariinid
* **title**: Tangerines

I'm still not too sure about the best course of action regarding the meaning of "title" and "original title", and if we need to swap them or not.  For sure "title" must **always** be present.

As always any idea and PR are welcome.

**Comment by alberanid** [comment]
Just another note: obviously "localized title" depends on your geographic area and what I get (**Tangerines - Mandarini**, from Italy) is different from what Travis CI gets (**Tangerines**, I guess from the US). See https://travis-ci.org/github/alberanid/imdbpy/jobs/767447230#L616

**Comment by frleder** [comment]
I think that mostly, where title != original title, the cover image often uses the same name as title. For me, title (universal title? international title?) makes sense the way it is.

However, when localized title is the original title, that is hard to find out. For me (Belgium), https://www.imdb.com/title/tt0382330/:
Title: As It Is in Heaven
Localized title: Så som i himmelen
No "original title". Localized title *is* the original title though, as we can see here: https://www.imdb.com/title/tt0382330/releaseinfo#akas

The only way to find it there, is iterating through all aka's and marking the title where it is tagged as "(original title)".
Also, currently only the first five-ish aka's, those on the reference page, are recorded. Maybe that would be the best approach?

**Comment by frleder** [comment]
Did some searching/testing, and I think this works best as it is right now, as this set of information is from the reference page - getting info from other sources does not make things clearer. Localized title might not be the best name, as it is often not explicitly localized, but will simply return the regular title, but otherwise it works.

The best way to get the original title for an end user, if you want to be sure of it, might be something like:

```
from imdb import IMDb

ia = IMDb()
i = IMDb('http')

movie = ia.get_movie('0382330')
movie['akas'] # five-ish akas
i.update(movie, 'akas')
movie['akas'] # complete list of akas
if(movie[ 'akas'][0].endswith("(original title)")):
	originaltitle = movie[ 'akas'][0].rpartition(" (original title)")[0]
```

**Comment by alberanid** [comment]
@frleder thanks for the analysis and the sample code.

Probable something like that could be introduced in the imdb.helpers module (I'll think about it and I will try to work on it in the next few weeks).

**Comment by alberanid** [comment]
I think I have improved the parsing of original and localized title.

Right now:
* **title** is always the "international title" (I think that most of the times it's the English title of the movie)
* **original title** is the title in the original language; there are now two parsers to extract it, since IMDb seems to write it in different places for different movies
* **localized title** is the title in your local language

In #329 I've also added the ability to specify the language you want. If not specified, apparently IMDb serves you the page using IP geolocalization, but it's an hit-and-miss.  So, if you want to always have **localized title** in your own language, use something like `ia = IMDb('http', language='de-DE')` for German.

Hope this helps.

I'm closing this issue; if there are other ideas or problems, feel free to open a new one.

**Comment by facundobatista** [comment]
Thanks for this work!!!

**Comment by Rabelaiss** [comment]
Excuse me if I reply to an old issue, but I'm having a problem related to it.
There is an english movie titled "Eternal sunshine of the spotless mind" which in Italy has been translated to "Se mi lasci ti cancello". I'd like to search for the movie using the italian title, and then get the localized title in italian. I tried creating an instance of the Cinemagoer class with the parameter `language='it-IT'`, but then `movie['localized title']` contains the title in english instead of the italian title. See code below

```
from imdb import Cinemagoer
ia = Cinemagoer(language='it-IT')
movies = ia.search_movie('se mi lasci ti cancello')

[<Movie id:13782316[http] title:_Se mi lasci ti cancello (None)_>,
 <Movie id:0338013[http] title:_Eternal Sunshine of the Spotless Mind (None)_>,
 <Movie id:21423006[http] title:_Se Mi Lasci Ti Sposo (None)_>,
 ...
```

The correct movie is the second one, so I select it, update it and print all titles, but none of them is in italian. Am I doing something wrong?

```
movie = movies[1]
ia.update(movie)
for key in a[1].keys():
    if 'title' in key:
        print(f'{key}\n{movie[key]}\n')

title
Eternal Sunshine of the Spotless Mind

original title
Eternal Sunshine of the Spotless Mind

localized title
Eternal Sunshine of the Spotless Mind

canonical title
Eternal Sunshine of the Spotless Mind

long imdb title
Eternal Sunshine of the Spotless Mind (2004)

long imdb canonical title
Eternal Sunshine of the Spotless Mind (2004)

smart canonical title
Eternal Sunshine of the Spotless Mind

smart long imdb canonical title
Eternal Sunshine of the Spotless Mind (2004)
```

**Comment by Rabelaiss** [comment]
Many thanks @frleder !
I replaced `language` with `languages` and it works! Not sure why it doesn't work for you though 🤔 Also, I tried with `help(ia)` but it doesn't print the arguments (such as `languages`) and their descriptions.

```
from imdb import Cinemagoer
ia = Cinemagoer(languages='it-IT')
movie = ia.search_movie('se mi lasci ti cancello')[0]
ia.update(movie)
for key in ['title','original title','localized title']:
    print(f'key: {key}\n{movie[key]}\n')

key: title
Eternal Sunshine of the Spotless Mind

key: original title
Eternal Sunshine of the Spotless Mind

key: localized title
Se mi lasci ti cancello
```
