### ISSUE TITLE
No longer works without lxml

### ISSUE THREAD

**Issue by miigotu** [alberanid/imdbpy#259]
Since the module no longer works without lxml, this cannot be used as a pure-python solution and relies on the c-extensions of lxml.

Is there a way around this? How can I help?

**Comment by alberanid** [comment]
I think it's true that we have now a strict dependency on lxml, but I may be wrong; for sure @uyar knows better.

Personally, I do not think it's a huge limit, to be honest, and I fear that supporting both lxml and - for example - BeautifulSoup (as it was some years ago) is more trouble that it's worth.

**Comment by uyar** [comment]
Oh right, I was going to respond but forgot. The underlying parser package (piculet) works both with lxml and elementtree. The latter is part of the standard library. The problem is that elementtree supports only a limited set of XPath expressions and there are some parsers in IMDbPY that use those features. It should be possible to rewrite those parsers using only the subset supported by elementtree, in which case IMDbPY would also work without lxml while using it if available. This could be done one parser at a time, no need to replace all such parsers at once.

**Comment by miigotu** [comment]
I went through and updated everything to work with the newest piculet last night and it still failed with invalid predicated x.X

The problem with lxml is I can't bundle it with SickChill, because it relies on compiled C extensions.

In the past, beautifulsoup was great for me, it parses xml and HTML well without needing anything that isn't pure python. Maybe I can add a new parser using that.

**Comment by uyar** [comment]
Updating piculet won't help since the issue is lacking xpath support in elementtree. Basing parsers on beautifulsoup would be too much work because it also doesn't support xpath. We had to implement an xpath processor for it back then. That implantation could probably be adapted to the new beautifulsoup version. Or maybe look for a pure Python xpath implementation? I think rewriting parsers that use unsupported clauses like xpath functions (e.g. starts-with) is the path of least resistance. Another option would be too add support for these to piculet.

**Comment by miigotu** [comment]
I'll look into a pure python xpath here when I get back to a PC.
https://github.com/jerith/xpathlet seems like it might be a good start point, maybe I'll fork it and update it if necessary.

I was giving up last night and looking at another IMDb parser lol.

**Comment by alberanid** [comment]
> I think rewriting parsers that use unsupported clauses like xpath functions (e.g. starts-with) is the path of least resistance. Another option would be too add support for these to piculet.

I agree.  Using only elementtree would be cool, but I don't know how much work it's required.

In any case, I don't think it has a high priority (but obviously any improvement is welcome)

**Comment by miigotu** [comment]
We'll see if I can get around to it, hopefully. Another project that uses their json was able to get me past this for now. I'll try and help when I can.
