### ISSUE TITLE
Popular movies

### ISSUE THREAD

**Issue by GrbavaCigla** [alberanid/imdbpy#260]
Hi,

Is there something like `get_top250_movies` but for popular movies: https://www.imdb.com/chart/moviemeter/

Thanks in advance!

**Comment by alberanid** [comment]
A parser is not present, but since the page looks very similar to the one of the top250 I guess it's easy to add.

I'll probably work on it in the next weeks, unless someone else wants to help (in that case I can explain what's needed).

Let me know.

The pages that can probably be parsed easily are:
* /chart/moviemeter
* /chart/tvmeter
* /chart/toptv
* /india/top-rated-indian-movies

**Comment by GrbavaCigla** [comment]
I can do it. I thought that of a function like `get_top250_movies`, but takes 2 parameters, one the `limit` (default 250) and second is the `chart` (`moviemeter`, `tvmete`, `toptv`, ...).
That would be a lot more flexible.

**Comment by alberanid** [comment]
@GrbavaCigla: that's great, thanks!

I guess that the limit parameter is not needed, since those lists have a fixed length and we don't need no know in advance how many items they contain.

Anyway, it's possible (but I'm not 100% sure) that we don't even need a new function.

In the `imdb/parser/http/__init__.py` file there is the **_get_top_bottom_movies** method that is used to parse both top and bottom lists.

It receives the **kind** parameter, which at the moment can be "top" or "bottom".
I guess it could be extended to support these other pages.

In the `imdb/__init__.py` file we can then add some new methods copying **get_top250_movies** (e.g.: we can add **get_moviemeter_movies**)

We can probably simplify a little the **DOMHTMLTop250Parser** class in the `imdb.parser.http.topBottomParser.py` file: right now it's customized for the top/bottom lists just changing the name of a key in the dictionary it returns. It makes sense to make it generic so that all of these functions can just use the same class without the need to customize it. (yes, the code is a little messy... the first commit was made 15 years ago, and meanwhile a lot of things changed).

PS: I notice now that a lot of URLs like imdbURL_top250 are duplicated in the imdb modules and in the IMDbBase class; I'm not sure but I think that the former are obsoletes. Maybe. Maybe not.

If something is not clear, let me know

**Comment by GrbavaCigla** [comment]
Nice, I think I understood. I will fork it and start working on it.

**Comment by GrbavaCigla** [comment]
I think I have working solution, but I cannot build it:
```sh
Traceback (most recent call last):
  File "setup.py", line 83, in <module>
    featSQLAlchemy = setuptools.dist.Feature(
AttributeError: module 'setuptools.dist' has no attribute 'Feature'

```

**Comment by GrbavaCigla** [comment]
https://github.com/GrbavaCigla/imdbpy/commit/5f8c6769ceebaa9bc674e29817816a64f3f73f0e
I didn't add raw movies to Movie objects yet

**Comment by alberanid** [comment]
> I think I have working solution, but I cannot build it:

Which Python version are you using?

Installing it, I see some warnings that I guess we'll have to address, soon:
```
$ python ./setup.py develop
./setup.py:83: DistDeprecationWarning: Features are deprecated and will be removed in a future version. See https://github.com/pypa/setuptools/issues/65.
  featSQLAlchemy = setuptools.dist.Feature(
./setup.py:163: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Created locale for: ar bg de en es fr it pt_BR tr.
/usr/lib/python3.8/distutils/core.py:108: DistDeprecationWarning: Features are deprecated and will be removed in a future version. See https://github.com/pypa/setuptools/issues/65.
  _setup_distribution = dist = klass(attrs)
```

For the development, lately I like to use [pipenv](https://pipenv.pypa.io/en/latest/)

To prepare the environment I did just once:
* mkdir imdbpy-pipenv3.8
* cd imdbpy-pipenv3.8
* pipenv --python python3.8
* pipenv shell # this will take you to a virtualenv shell
* pip install pytest # install some useful packages
* pip install twine # install some useful packages
* cd ~/git/imdbpy/ # move to where the IMDbPY repository is
* python setup.py develop # install it in development mode

After that, when I start the development I simply:
* cd imdbpy-pipenv3.8
* pipenv shell
* cd ~/git/imdbpy/
* *change stuff and test it*

Thanks for the pull-request, I'll review it as soon as possible, and try to figure out what to do with ranktext.

PS: what do you mean with "I didn't add raw movies to Movie objects yet"?

**Comment by GrbavaCigla** [comment]
I will try it, thanks!
> what do you mean with "I didn't add raw movies to Movie objects yet?

I resolved it, it is now fixed

**Comment by alberanid** [comment]
I've added some tests, the ability to parse the top 250 Indian movies and merged it.

I've added your name to the list of credits, thanks!

(at some point we'll need to do a new release)
