### ISSUE TITLE
ERROR: Could not install packages due to an EnvironmentError

### ISSUE THREAD

**Issue by syshd** [alberanid/imdbpy#310]
#### Issue description

*write the description here*

#### Version of IMDbPY, Python and OS

**NOTICE: please always try the latest version from the repository before submitting a bug.**

- **Python:** Python 3.9.2
- **IMDbPY:** IMDbPY 2020.9.25 Unable to Install

- **OS:** system='Windows', node='DESKTOP-S832HD1', release='10', version='10.0.19041', machine='AMD64'

#### Steps to reproduce the issue

- pip install IMDbPY

#### What's the expected result?

-I'm Unable to install imdbpy on my machine

#### What's the actual result?

- pip install IMDbPY
Collecting IMDbPY
  Using cached IMDbPY-2020.9.25-py3-none-any.whl (304 kB)
Requirement already satisfied: lxml in c:\users\admin\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from IMDbPY) (4.6.3)
Requirement already satisfied: SQLAlchemy in c:\users\admin\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from IMDbPY) (1.4.3)
Requirement already satisfied: greenlet!=0.4.17; python_version >= "3" in c:\users\admin\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from SQLAlchemy->IMDbPY) (1.0.0)
Installing collected packages: IMDbPY

ERROR: Could not install packages due to an EnvironmentError: [WinError 206] The filename or extension is too long: 'C:\\Users\\Admin\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python39\\site-packages\\home\\da\\.local\\share\\virtualenvs\\imdbpy-pipenv3.8-Ei8gA4to\\lib\\python3.8\\site-packages\\imdb\\locale\\ar\\LC_MESSAGES'

#### Additional details

-

**Comment by alberanid** [comment]
Hi @syshd , this is odd.
I can confirm that the IMDbPY-2020.9.25-py3-none-any.whl wheel file (basically, a zip), contains some content that should not be there:
```
$ unzip IMDbPY-2020.9.25-py3-none-any.whl 
Archive:  IMDbPY-2020.9.25-py3-none-any.whl
  inflating: IMDbPY-2020.9.25.data/scripts/get_character.py  
  inflating: IMDbPY-2020.9.25.data/scripts/get_company.py  
  inflating: IMDbPY-2020.9.25.data/scripts/get_first_character.py  
  inflating: IMDbPY-2020.9.25.data/scripts/get_first_company.py  
  inflating: IMDbPY-2020.9.25.data/scripts/get_first_movie.py  
  inflating: IMDbPY-2020.9.25.data/scripts/get_first_person.py  
  inflating: IMDbPY-2020.9.25.data/scripts/get_keyword.py  
  inflating: IMDbPY-2020.9.25.data/scripts/get_movie.py  
  inflating: IMDbPY-2020.9.25.data/scripts/get_person.py  
  inflating: IMDbPY-2020.9.25.data/scripts/get_top_bottom_movies.py  
  inflating: IMDbPY-2020.9.25.data/scripts/imdbpy2sql.py  
  inflating: IMDbPY-2020.9.25.data/scripts/s32imdbpy.py  
  inflating: IMDbPY-2020.9.25.data/scripts/search_character.py  
  inflating: IMDbPY-2020.9.25.data/scripts/search_company.py  
  inflating: IMDbPY-2020.9.25.data/scripts/search_keyword.py  
  inflating: IMDbPY-2020.9.25.data/scripts/search_movie.py  
  inflating: IMDbPY-2020.9.25.data/scripts/search_person.py  
  inflating: home/da/.local/share/virtualenvs/imdbpy-pipenv3.8-Ei8gA4to/lib/python3.8/site-packages/imdb/locale/imdbpy-ar.po  
  inflating: home/da/.local/share/virtualenvs/imdbpy-pipenv3.8-Ei8gA4to/lib/python3.8/site-packages/imdb/locale/imdbpy-bg.po  
  inflating: home/da/.local/share/virtualenvs/imdbpy-pipenv3.8-Ei8gA4to/lib/python3.8/site-packages/imdb/locale/imdbpy-de.po  
  inflating: home/da/.local/share/virtualenvs/imdbpy-pipenv3.8-Ei8gA4to/lib/python3.8/site-packages/imdb/locale/imdbpy-en.po  
  inflating: home/da/.local/share/virtualenvs/imdbpy-pipenv3.8-Ei8gA4to/lib/python3.8/site-packages/imdb/locale/imdbpy-es.po  
  inflating: home/da/.local/share/virtualenvs/imdbpy-pipenv3.8-Ei8gA4to/lib/python3.8/site-packages/imdb/locale/imdbpy-fr.po  
  inflating: home/da/.local/share/virtualenvs/imdbpy-pipenv3.8-Ei8gA4to/lib/python3.8/site-packages/imdb/locale/imdbpy-it.po  
  inflating: home/da/.local/share/virtualenvs/imdbpy-pipenv3.8-Ei8gA4to/lib/python3.8/site-packages/imdb/locale/imdbpy-pt_BR.po  
  inflating: home/da/.local/share/virtualenvs/imdbpy-pipenv3.8-Ei8gA4to/lib/python3.8/site-packages/imdb/locale/imdbpy-tr.po  
  inflating: home/da/.local/share/virtualenvs/imdbpy-pipenv3.8-Ei8gA4to/lib/python3.8/site-packages/imdb/locale/imdbpy.pot  
  inflating: home/da/.local/share/virtualenvs/imdbpy-pipenv3.8-Ei8gA4to/lib/python3.8/site-packages/imdb/locale/ar/LC_MESSAGES/imdbpy.mo  
  inflating: home/da/.local/share/virtualenvs/imdbpy-pipenv3.8-Ei8gA4to/lib/python3.8/site-packages/imdb/locale/bg/LC_MESSAGES/imdbpy.mo  
  inflating: home/da/.local/share/virtualenvs/imdbpy-pipenv3.8-Ei8gA4to/lib/python3.8/site-packages/imdb/locale/de/LC_MESSAGES/imdbpy.mo  
  inflating: home/da/.local/share/virtualenvs/imdbpy-pipenv3.8-Ei8gA4to/lib/python3.8/site-packages/imdb/locale/en/LC_MESSAGES/imdbpy.mo  
  inflating: home/da/.local/share/virtualenvs/imdbpy-pipenv3.8-Ei8gA4to/lib/python3.8/site-packages/imdb/locale/es/LC_MESSAGES/imdbpy.mo  
  inflating: home/da/.local/share/virtualenvs/imdbpy-pipenv3.8-Ei8gA4to/lib/python3.8/site-packages/imdb/locale/fr/LC_MESSAGES/imdbpy.mo  
  inflating: home/da/.local/share/virtualenvs/imdbpy-pipenv3.8-Ei8gA4to/lib/python3.8/site-packages/imdb/locale/it/LC_MESSAGES/imdbpy.mo  
  inflating: home/da/.local/share/virtualenvs/imdbpy-pipenv3.8-Ei8gA4to/lib/python3.8/site-packages/imdb/locale/pt_BR/LC_MESSAGES/imdbpy.mo  
  inflating: home/da/.local/share/virtualenvs/imdbpy-pipenv3.8-Ei8gA4to/lib/python3.8/site-packages/imdb/locale/tr/LC_MESSAGES/imdbpy.mo  
  inflating: imdb/Character.py       
  inflating: imdb/Company.py         
  inflating: imdb/Movie.py           
  inflating: imdb/Person.py          
  inflating: imdb/__init__.py        
  inflating: imdb/_exceptions.py     
  inflating: imdb/_logging.py        
  inflating: imdb/cli.py             
  inflating: imdb/helpers.py         
  inflating: imdb/linguistics.py     
  inflating: imdb/utils.py           
  inflating: imdb/version.py         
  inflating: imdb/locale/__init__.py  
  inflating: imdb/locale/generatepot.py  
  inflating: imdb/locale/msgfmt.py   
  inflating: imdb/locale/rebuildmo.py  
  inflating: imdb/parser/__init__.py  
  inflating: imdb/parser/logging.py  
  inflating: imdb/parser/http/__init__.py  
  inflating: imdb/parser/http/companyParser.py  
  inflating: imdb/parser/http/listParser.py  
  inflating: imdb/parser/http/logging.py  
  inflating: imdb/parser/http/movieParser.py  
  inflating: imdb/parser/http/personParser.py  
  inflating: imdb/parser/http/piculet.py  
  inflating: imdb/parser/http/searchCompanyParser.py  
  inflating: imdb/parser/http/searchKeywordParser.py  
  inflating: imdb/parser/http/searchMovieAdvancedParser.py  
  inflating: imdb/parser/http/searchMovieParser.py  
  inflating: imdb/parser/http/searchPersonParser.py  
  inflating: imdb/parser/http/topBottomParser.py  
  inflating: imdb/parser/http/utils.py  
  inflating: imdb/parser/s3/__init__.py  
  inflating: imdb/parser/s3/utils.py  
  inflating: imdb/parser/sql/__init__.py  
  inflating: imdb/parser/sql/alchemyadapter.py  
  inflating: imdb/parser/sql/dbschema.py  
  inflating: imdb/parser/sql/logging.py  
  inflating: IMDbPY-2020.9.25.dist-info/LICENSE.txt  
  inflating: IMDbPY-2020.9.25.dist-info/METADATA  
  inflating: IMDbPY-2020.9.25.dist-info/WHEEL  
  inflating: IMDbPY-2020.9.25.dist-info/entry_points.txt  
  inflating: IMDbPY-2020.9.25.dist-info/top_level.txt  
  inflating: IMDbPY-2020.9.25.dist-info/RECORD  
```

Everything from `home` should not be included in it.

We will try to understand what's going on.

I usually create the whl file with:
```
python3 setup.py sdist
python3 setup.py bdist_wheel
```

from inside a pipenv virtualenv.

If anyone has any idea about how to fix it, it would be great.

**Comment by Philippe-Cholet** [comment]
From what I understand, these mo/po/pot files are meant to be here but with a way shorter path (meaning excluding `home/da/.local/share/virtualenvs/imdbpy-pipenv3.8-Ei8gA4to/lib/python3.8/site-packages`).

There are important infos I did not know about there:
https://docs.python.org/3/distutils/setupscript.html#installing-additional-files
It seems to me that the wheel considers the absolute paths you gave him as relatives.

Maybe that give relative paths would be enough to solve this.
https://github.com/alberanid/imdbpy/blob/master/setup.py#L188 and below.
So I gave it a shot or two!

Being on Windows, I changed `'/'` to `os.path.sep` to have a chance...

    rebuildmo = importlib.import_module(os.path.join(REBUILDMO_DIR, REBUILDMO_NAME).replace(os.path.sep, '.'))

Without `distutils.sysconfig.get_python_lib()` (hence no need of `import distutils.sysconfig`)

    data_files.append(('imdb/locale', ['imdb/locale/imdbpy.pot']))
    data_files.append(('imdb/locale', ['imdb/locale/imdbpy-%s.po' % lang]))
    data_files.append((base_dir, files_found))

The build produced a wheel `IMDbPY-2021.2.24-py3-none-any.whl`, where data files are in `IMDbPY-2021.2.24.data\data\imdb\locale` which seems fine to me.

But maybe there is a reason to `distutils.sysconfig.get_python_lib()`...

**Comment by Philippe-Cholet** [comment]
I downloaded all available wheels (since IMDbPY 6.0), looked into the localization of the ".pot" file, and found this is an issue since the beggining.

    IMDbPY-6.0-py3-none-any.whl         usr/lib/python3/dist-packages/imdb/locale
    IMDbPY-6.2-py3-none-any.whl         usr/lib/python3/dist-packages/imdb/locale
    IMDbPY-6.3-py3-none-any.whl         usr/lib/python3/dist-packages/imdb/locale
    IMDbPY-6.4-py3-none-any.whl         usr/lib/python3/dist-packages/imdb/locale
    IMDbPY-6.4.1-py3-none-any.whl       usr/lib/python3/dist-packages/imdb/locale
    IMDbPY-6.5-py3-none-any.whl         usr/lib/python3/dist-packages/imdb/locale
    IMDbPY-6.6-py3-none-any.whl         home/da/imdbpy3_git/lib/python3.5/site-packages/imdb/locale
    IMDbPY-6.7-py3-none-any.whl         home/da/imdbpy3_git/lib/python3.5/site-packages/imdb/locale
    IMDbPY-6.8-py3-none-any.whl         home/da/.local/share/virtualenvs/imdbpy-pipenv3.6-MNLG6NU-/lib/python3.6/site-packages/imdb/locale
    IMDbPY-2020.9.25-py3-none-any.whl   home/da/.local/share/virtualenvs/imdbpy-pipenv3.8-Ei8gA4to/lib/python3.8/site-packages/imdb/locale

I tried to use localization with my installation of `IMDbPY-2020.9.25`, did not work or I misunderstood something. So I think localization does not work with wheel installation since the `5.1.1` version.

Another sad note, I tried with the wheel I made myself before, I does not work yet. So still investigating...

**Comment by Philippe-Cholet** [comment]
Well after some tests and reading I learnt [here](https://packaging.python.org/guides/distributing-packages-using-setuptools/#id56) `data_files` "is mostly useful if you need to install files which are used by other programs, which may be unaware of Python packages" and because of that is written outside of the package in a destination that may not be os-independant (so I guess that's why there was `distutils.sysconfig.get_python_lib()`), so it not just about relative/absolute paths. It seems to me `package_data` would be much more adequate here, and after some tests much more simple really.

So getting entirely rid of `data_files`, but adding `package_data = {'imdb.locale': ['imdbpy.pot', 'imdbpy-*.po', '*/LC_MESSAGES/imdbpy.mo']}` (the `*` represents any possible language ID) made **the pot/po/mo files in the right place** (alongside python files just like in the repository) both in the wheel and in the installation I made from it.

But there is still a sad note, I got an `UnicodeDecodeError` while I should have the translation. But in order to fail, it has to be trying, so there is progress.
```python
>>> import imdb.locale
>>> import gettext
>>> gettext.textdomain('imdbpy')
>>> _ = gettext.gettext
>>> import os
'imdbpy'
>>> _('animation-department')
'animation-department'
>>> os.environ['LANG'] = 'fr_FR'
>>> _('animation-department')
Traceback (most recent call last):
  File "<pyshell#59>", line 1, in <module>
    _('animation-department')
  File "C:\Program Files\Python37\lib\gettext.py", line 625, in gettext
    return dgettext(_current_domain, message)
  File "C:\Program Files\Python37\lib\gettext.py", line 588, in dgettext
    codeset=_localecodesets.get(domain))
  File "C:\Program Files\Python37\lib\gettext.py", line 533, in translation
    t = _translations.setdefault(key, class_(fp))
  File "C:\Program Files\Python37\lib\gettext.py", line 260, in __init__
    self._parse(fp)
  File "C:\Program Files\Python37\lib\gettext.py", line 421, in _parse
    catalog[str(msg, charset)] = str(tmsg, charset)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 5: ordinal not in range(128)
```

**Comment by Philippe-Cholet** [comment]
From my investigation with pdb, it seems the metadata (or catalog description as you wish) of the french .mo file (probably other langs too) is not parsed, hence "charset=UTF-8" is ignored and it leads to the default/wrong charset 'ascii' to decode non-ascii char like "é".
I had hard times figuring out I just had to uncomment "ast.literal_eval" in "msgfmt.py" to solve this entirely. It was commented out last year to make "the file compatible with python 2.7" but I don't see why since the function exists in py2.7 (at least in the documentation) and the error the commit was meant to fix was on another line entirely.

But I found out another error on the way. Global variables are tricky, so without clearing `MESSAGES` variable between calls of the `make` function, translations are partly mixed up... That was not an issue when a class MsgFmt was used in 2017.

**So @alberanid I think I solved the entire thing here, I'm gonna summarize the proposed solutions:**
* Get entirely rid of `data_files` and the `distutils.sysconfig` import in `setup.py` and replace with `package_data = {'imdb.locale': ['imdbpy.pot', 'imdbpy-*.po', '*/LC_MESSAGES/imdbpy.mo']}` in params. That way, locale files (pot/po/mo) are in the right place in the wheel and pip-installations from it, **solving this installation issue**, issue that exists since `imdbpy 5.1.1` or sooner.
* On windows, to build the wheel, I had to replace one `'/'` by `os.path.sep` in "setup.py".
* Start the `make` function in "imdb/locale/msgfmt.py" with `MESSAGES.clear()` (except it's not "py2.7-friendly" so `global MESSAGES; MESSAGES = {}` instead) in order to prevent translations to be mixed up when we call the `make` function multiple times just like we do in "setup.py" when building the wheel.
* In the same file, uncomment `l = ast.literal_eval(l)`. WIthout it, the "po header" is not parsed on my computer leading to some `UnicodeDecodeError` raised. Seem to be wrongly commented out last year to make the file "py2.7-friendly".

I'm gonna propose a pull request.

**Comment by alberanid** [comment]
@Philippe-Cholet thanks for the very detailed analysis!

I agree that the call to ast.literal_eval was probably commented out for an error.

Feel free to include in the PR the proposed changes and everything else you think could improve the code.

Thanks!
